---
- name: Install Docker and Docker Compose on all hosts
  hosts: all
  become: yes
  tasks:

    # === Ubuntu ===
    - name: Update APT cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages for Docker (Ubuntu)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key (Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repo (Ubuntu)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Engine (Ubuntu)
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    # === Amazon Linux ===
    - name: Install Docker (Amazon Linux)
      yum:
        name: docker
        state: latest
      when: ansible_distribution == "Amazon"

    # === Common tasks for all OS ===
    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # === Docker Compose ===
    - name: Get latest Docker Compose release version
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: compose_release

    - name: Set Docker Compose version
      set_fact:
        compose_version: "{{ compose_release.json.tag_name }}"

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create symlink for docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: yes
