---
- name: Deploy MongoDB using Docker Compose
  hosts: mongo
  become: yes
  vars:
    mongo_compose_dir: /opt/mongodb
    mongo_compose_file: compose.yaml

  tasks:
    - name: Create directory for MongoDB Docker Compose project
      file:
        path: "{{ mongo_compose_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy compose.yaml to target host
      copy:
        src: "{{ mongo_compose_file }}"
        dest: "{{ mongo_compose_dir }}/compose.yaml"
        mode: '0644'

    - name: Verify Docker is installed
      command: docker --version
      register: docker_check
      changed_when: false

    - name: Verify Docker Compose is installed
      command: docker-compose --version
      register: compose_check
      changed_when: false

    - name: Run MongoDB container using docker compose
      command: docker compose -f compose.yaml up -d
      args:
        chdir: "{{ mongo_compose_dir }}"
