services:
  frontend:
    image: robic07/mern-frontend:latest
    expose:
      - 3000
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # ✅ FIXED
    depends_on:
      - frontend
    networks:
      - webnet

networks:
  webnet:
