name: Build and Deploy via Bastion

on:
  push:
    branches:
      - main          # ✅ Trigger on push to main
  workflow_dispatch:   # ✅ Manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ====== Docker Hub Login ======
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ====== Build & Push Backend ======
    - name: Build backend image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest ./backend

    - name: Push backend image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest

    # ====== Build & Push Frontend ======
    - name: Build frontend image
      run: docker build --build-arg VITE_SERVER_HOSTNAME=$HOSTNAME -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest ./frontend

    - name: Push frontend image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend:latest

    # ====== SSH to Bastion and Run Ansible Playbooks ======
    - name: Deploy via Ansible from Bastion
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.BASTION_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ansible
          
          # Deploy backend
          ansible-playbook -i inventory.ini ../mern-gallery-sample-app/backend-instance/playbook.yaml --limit backend

          # Deploy frontend
          ansible-playbook -i inventory.ini ../mern-gallery-sample-app/frontend-instance/playbook.yaml --limit frontend
